### ISSUE TITLE
Implement Routes and Pages for Home and User Authentication (Register, Complete Registration, Login, Password Reset, Complete Password Reset)

### ISSUE THREAD

**Issue by TKanX** [MPC-Lab-X/MPC-Lab-X-web#1]
### Tasks:

Implement the following features, routes and corresponding view templates (`EJS`):

1. **Home Page (`/`)**:

   - [x] The main landing page of the website, providing basic introduction and navigation.
   - [x] An example question generator that can select and generate example questions.

2. User Authentication Pages:

   - [x] **Register Page (`/register`)**
   - [x] **Complete Registration Page (`/register/complete`)**
   - [x] **Login Page (`/login`)**
   - [x] **Password Reset Page (`/password-reset`)**
   - [x] **Complete Password Reset Page (`/password-reset/complete`)**
